# Generated by Django 3.2.6 on 2021-10-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('uemail', models.EmailField(max_length=254)),
                ('upassword', models.CharField(max_length=30)),
                ('uconfirmpassword', models.CharField(max_length=30)),
                ('uaddress', models.CharField(max_length=90)),
            ],
        ),
    ]
